"use client";
// Komponen Next.js untuk memuat gambar yang dioptimalkan.
import Image from "next/image";
// Link internal agar perpindahan halaman project tetap dikelola Next.js.
import Link from "next/link";
// Ikon yang digunakan pada tombol dan informasi section.
import { ArrowDownRight, ArrowUpRight, Check, ExternalLink, Mail, MapPin, Send } from "lucide-react";
// Animasi reveal untuk kartu project ketika masuk viewport.
import { motion, useReducedMotion } from "motion/react";
// Data portfolio yang digunakan oleh seluruh section.
import { achievements, certificates, education, experience, personalInfo, projects, skills, socialLinks, stats } from "@/data/portfolio";
// Hook dan tipe event untuk state interaksi client-side.
import { FormEvent, useEffect, useState } from "react";

// Representasi ikon GitHub sederhana yang konsisten dengan gaya action link.
function Github({ size }: { size: number }) { return <span className="action-glyph" style={{ fontSize: size * 0.65 }}>GH</span>; }
// Path gambar profil yang digunakan pada bagian hero.
const heroImageUrl = "/images/profil_keren.jpeg";
const revealViewport = { once: true, amount: 0.18 };
function revealProps(reducedMotion: boolean, delay = 0) { return { initial: reducedMotion ? { opacity: 1 } : { opacity: 0, y: 24, filter: "blur(4px)" }, whileInView: { opacity: 1, y: 0, filter: "blur(0px)" }, viewport: revealViewport, transition: reducedMotion ? { duration: 0 } : { duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] as const } }; }

// Bagian pembuka yang memperkenalkan identitas, fokus, dan ajakan tindakan.
export function Hero() { return <section className="hero wrap" id="top"><div className="hero-copy"><p className="eyebrow reveal">Software engineer / designer <span className="status-dot" /> open to work</p><h1 className="hero-title reveal delay-1">Making AI engineer<br /><em>valuable</em> for the web..</h1><p className="hero-intro reveal delay-2">{personalInfo.bio}</p><div className="hero-actions reveal delay-3"><a className="button button-dark" href="#work">See my work <ArrowDownRight size={17} /></a><a className="text-link" href={`mailto:${personalInfo.email}`}>Get in touch <ArrowUpRight size={15} /></a></div><div className="hero-meta reveal delay-3"><span><MapPin size={14} /> {personalInfo.location}</span><span>{personalInfo.focus}</span></div></div><div className="hero-visual reveal delay-2"><div className="portrait-frame"><div className="portrait-art"><Image src={heroImageUrl} alt="Profile portrait" fill priority sizes="(max-width: 700px) 80vw, 390px" /><span className="portrait-caption">Akhmad Roufun Aziz</span></div></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="floating-note note-top">Years Old<br /><strong>16</strong></div><div className="floating-note note-bottom">My name is<br /><strong>Akhmad Roufun Aziz.</strong></div></div><div className="scroll-cue"><span>Scroll to explore</span><ArrowDownRight size={16} /></div></section>; }
// Menampilkan empat metrik ringkas dari data portfolio.
export function Stats() { const reducedMotion = useReducedMotion(); return <div className="stats wrap">{stats.map(([value, label], index) => <motion.div className="stat" key={label} {...revealProps(Boolean(reducedMotion), index * 0.07)}><strong>{value}</strong><span>{label}</span></motion.div>)}</div>; }
// Menampilkan konteks singkat, deskripsi, dan fakta utama tentang pemilik portfolio.
export function About() { const reducedMotion = useReducedMotion(); return <section className="section wrap about-section" id="about"><SectionLabel number="01" label="A little about me" title="About me" /><div className="about-grid"><motion.div className="about-lead" {...revealProps(Boolean(reducedMotion), 0.08)}><p>I&apos;am a developer and a vocational high school student majoring in Software Engineering, with a keen focus on the details that enable AI to function at its full potential in software development.</p></motion.div><motion.div className="about-body" {...revealProps(Boolean(reducedMotion), 0.16)}><p>I like working across the whole product: asking better questions, shaping a clear interface, then writing the code that makes it hold together. I&apos;m at my best when a messy idea becomes a useful, well-made thing.</p><p>Outside the browser, you&apos;ll find me collecting references, learning in public, and looking for the next problem worth solving.</p><div className="fact-grid"><Fact label="Based in" value={personalInfo.location} /><Fact label="Education" value={personalInfo.education} /><Fact label="Focus" value="Web development" /><Fact label="Role" value="Student / developer" /></div></motion.div></div></section>; }
// Komponen kecil untuk menampilkan satu label dan nilai fakta.
function Fact({ label, value }: { label: string; value: string }) { return <div className="fact"><span>{label}</span><strong>{value}</strong></div>; }
// Menampilkan teknologi berdasarkan kategori dan ticker teknologi berjalan.
export function Skills() { const reducedMotion = useReducedMotion(); return <section className="section skills-section" id="skills"><div className="wrap"><SectionLabel number="02" label="What I use" title="Tools for turning ideas into interfaces." /><div className="skills-grid">{skills.map((group, index) => <motion.div className="skill-group" key={group.category} {...revealProps(Boolean(reducedMotion), index * 0.08)}><div className="skill-heading"><span>0{index + 1}</span><h3>{group.category}</h3></div><div className="skill-list">{group.items.map((item) => <span key={item}>{item}</span>)}</div></motion.div>)}</div></div><div className="marquee"><div className="marquee-track">{[...skills.flatMap((group) => group.items), ...skills.flatMap((group) => group.items)].map((item, index) => <span key={`${item}-${index}`}>{item}<b>✳</b></span>)}</div></div></section>; }
// Menampilkan pengalaman dalam bentuk timeline beserta teknologi tiap peran.
export function Experience() { const reducedMotion = useReducedMotion(); return <section className="section wrap experience-section"><SectionLabel number="03" label="The path so far" title="Experience" /><div className="timeline">{experience.map((item, index) => <motion.article className="timeline-item" key={item.year} {...revealProps(Boolean(reducedMotion), index * 0.1)}><div className="timeline-date">{item.year}</div><div className="timeline-main"><h3>{item.role}</h3><p className="timeline-company">{item.company}</p><p>{item.description}</p><div className="tag-row">{item.tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div></motion.article>)}</div></section>; }
// Menampilkan kartu project dengan animasi saat kartu terlihat di viewport.
export function Projects() { const reducedMotion = useReducedMotion(); return <section className="section wrap projects-section" id="work"><SectionLabel number="04" label="Selected work" title="A few things I&apos;ve made." /><div className="project-grid">{projects.map((project, index) => <motion.article className={`project-card ${project.featured ? "featured" : "supporting"} ${project.color}`} key={project.slug} {...revealProps(Boolean(reducedMotion), index * 0.08)}><div className="project-image"><Image src={project.image} alt={`${project.title} project preview`} fill sizes="(max-width: 700px) 100vw, 50vw" /><span className="project-number">{project.number}</span><span className="project-image-label">{project.featured ? "Featured case study" : "Selected experiment"}</span></div><div className="project-content"><div><p className="project-category">{project.category}</p><h3>{project.title}</h3><p>{project.description}</p><p className="project-detail-line">A focused build exploring product clarity, useful motion, and a durable visual system.</p></div><div className="project-footer"><div className="tag-row">{project.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div><div className="project-actions"><a href={project.githubUrl} target="_blank" rel="noreferrer" aria-label={`${project.title} on GitHub`}><Github size={15} /> GitHub</a><a href={project.liveUrl} target="_blank" rel="noreferrer" aria-label={`View ${project.title} live demo`}>Live demo <ExternalLink size={14} /></a><Link href={`/projects/${project.slug}`} className="circle-link" aria-label={`View ${project.title} details`}><ArrowUpRight size={19} /></Link></div></div></div></motion.article>)}</div></section>; }
// Menampilkan daftar pencapaian pada section dengan tema gelap.
export function Achievements() { const reducedMotion = useReducedMotion(); return <section className="section dark-section"><div className="wrap"><SectionLabel number="05" label="Small wins" title="Achievements" light /><div className="achievement-list">{achievements.map((item, index) => <motion.div className="achievement" key={item.title} {...revealProps(Boolean(reducedMotion), index * 0.1)}><span className="achievement-year">{item.year}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><span className="achievement-level">{item.level}</span></motion.div>)}</div></div></section>; }
// Menampilkan sertifikat dan mengelola modal preview gambar yang dipilih.
export function Certificates() { const [selected, setSelected] = useState<string | null>(null); const reducedMotion = useReducedMotion(); useEffect(() => { if (!selected) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); }; document.addEventListener("keydown", closeOnEscape); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", closeOnEscape); document.body.style.overflow = ""; }; }, [selected]); return <section className="section wrap certificates-section"><SectionLabel number="06" label="Proof of practice" title="Certificates" /><div className="certificate-grid">{certificates.map((item, index) => <motion.button className="certificate" key={item.title} onClick={() => setSelected(item.image)} aria-label={`Open ${item.title} certificate`} {...revealProps(Boolean(reducedMotion), index * 0.1)}><div className="certificate-image"><Image src={item.image} alt={`${item.title} certificate`} fill sizes="(max-width: 700px) 100vw, 40vw" /></div><span>{item.issuer} · {item.year}</span><strong>{item.title}</strong></motion.button>)}</div>{selected && <div className="modal" role="dialog" aria-modal="true" aria-label="Certificate preview" onClick={() => setSelected(null)}><div className="modal-content" onClick={(event) => event.stopPropagation()}><button className="modal-close" autoFocus onClick={() => setSelected(null)} aria-label="Close certificate preview">×</button><Image src={selected} alt="Expanded certificate" width={900} height={620} /></div></div>}</section>; }
// Menampilkan satu entri pendidikan formal dari data portfolio.
export function Education() { const reducedMotion = useReducedMotion(); return <section className="section wrap education-section"><SectionLabel number="07" label="Where it started" title="Education" /><motion.div className="education-card" {...revealProps(Boolean(reducedMotion))}><span>{education[0].year}</span><div><h3>{education[0].school}</h3><p className="timeline-company">{education[0].major}</p><p>{education[0].description}</p></div><Check size={22} /></motion.div></section>; }
// Menampilkan informasi kontak dan formulir pesan sederhana di sisi client.
export function Contact() { const [sent, setSent] = useState(false); const reducedMotion = useReducedMotion(); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); } return <section className="section contact-section" id="contact"><div className="wrap contact-grid"><div><SectionLabel number="08" label="Start a conversation" title="Let&apos;s make<br /><em>something useful.</em>" light /><p className="contact-copy">Have a project, a question, or just a good idea? My inbox is open.</p><div className="contact-email"><Mail size={18} /><a href={`mailto:${personalInfo.email}`}>{personalInfo.email}</a></div><div className="socials">{socialLinks.map((link) => <a href={link.href} key={link.label} target="_blank" rel="noreferrer">{link.label} <ArrowUpRight size={14} /></a>)}</div></div><motion.form className="contact-form" onSubmit={submit} {...revealProps(Boolean(reducedMotion), 0.12)}>{sent ? <div className="form-success"><Check size={28} /><h3>Message received.</h3><p>Thanks for reaching out. I&apos;ll get back to you soon.</p><button type="button" className="button button-light" onClick={() => setSent(false)}>Send another</button></div> : <><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" placeholder="Tell me a little about the project..." rows={4} /></label><button className="button button-lime" type="submit">Send message <Send size={16} /></button></>}</motion.form></div></section>; }
// Footer berisi identitas singkat, teknologi yang digunakan, dan tahun copyright.
export function Footer() { return <footer className="footer wrap"><a className="brand" href="#top"><span className="brand-mark">AR</span><span>Akhmad Roufun Aziz</span></a><span>Designed &amp; built with Next.js</span><span>© 2026</span></footer>; }
// Header section yang dapat digunakan ulang dengan mode warna terang atau gelap.
function SectionLabel({ number, label, title, light = false }: { number: string; label: string; title: string; light?: boolean }) { const reducedMotion = useReducedMotion(); return <motion.div className={`section-heading ${light ? "light" : ""}`} {...revealProps(Boolean(reducedMotion))}><div className="heading-kicker"><span>{number}</span><span>{label}</span></div><h2 dangerouslySetInnerHTML={{ __html: title }} /></motion.div>; }
